services:
  - type: web
    name: qr-work-sessions-api
    env: docker
    plan: free
    autoDeploy: true
    rootDir: backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: qr-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: SEED_TOKEN
        generateValue: true
databases:
  - name: qr-db
    plan: free
